In [1]:
list1 = [1,2,4]

In [2]:
list1

[1, 2, 4]

In [3]:
import numpy as np

# Basics

In [4]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [5]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr1.shape

(2, 5)

In [8]:
arr1 = np.array([[1,2.6,3,4,5],[6,7,8,9,10]])
print(arr1)

[[ 1.   2.6  3.   4.   5. ]
 [ 6.   7.   8.   9.  10. ]]


In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype="float64")
print(arr1)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr1 = np.array([1,4,7,8,3,7,16,12,5,18,11,6])
arr1

array([ 1,  4,  7,  8,  3,  7, 16, 12,  5, 18, 11,  6])

In [13]:
arr1.shape

(12,)

In [14]:
arr1 = arr1.reshape(3,4)
arr1

array([[ 1,  4,  7,  8],
       [ 3,  7, 16, 12],
       [ 5, 18, 11,  6]])

In [15]:
arr1 = np.zeros((3,6))   #all elements are assigned zeroes
arr1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr1 = np.zeros((3,6))   #all elements are not assigned zeroes (only memory allocated)
arr1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
arr1.dtype

dtype('float64')

In [19]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
arr1+arr1

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [21]:
arr1-arr1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
arr1*arr1        #Not same as MATRIX MULTIPLICATION

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [23]:
arr1/arr1  

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
arr1**arr1

array([[         1,          4,         27,        256,       3125],
       [     46656,     823543,   16777216,  387420489, 1410065408]])

In [25]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

In [27]:
(1/arr1).dtype

dtype('float64')

# Slicing

In [28]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [29]:
arr = arr2[3:5]
arr

array([4, 5])

In [30]:
arr[0] = 8
arr

array([8, 5])

In [31]:
arr2 #original list changed

array([1, 2, 3, 8, 5])

In [32]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [33]:
arr = arr2[3:5].copy()   #now it will not CHANGE
arr

array([4, 5])

In [34]:
arr[0] = 8
arr

array([8, 5])

In [35]:
arr2

array([1, 2, 3, 4, 5])

# Matrix Operations

In [36]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
arr1.sum(axis=0)              #SUM of all elements in a COLUMN

array([ 7,  9, 11, 13, 15])

In [38]:
arr1.sum(axis=1)              #SUM of all elements in a ROW

array([15, 40])

In [39]:
arr2 = arr1.transpose()
arr2

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [40]:
np.dot(arr1, arr2)

array([[ 55, 130],
       [130, 330]])

In [41]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.cross(arr1,arr1)

array([[0, 0, 0],
       [0, 0, 0]])

In [43]:
arr1 = np.array([[5,9,6], [5,2,8]])
arr1

array([[5, 9, 6],
       [5, 2, 8]])

In [44]:
np.sort(arr1)     #By default AXIS = 1
arr1

array([[5, 9, 6],
       [5, 2, 8]])

In [45]:
np.sort(arr1, axis=0)
arr1

array([[5, 9, 6],
       [5, 2, 8]])

In [46]:
np.sort(arr1, axis=1, kind = 'selectionsort')  #We can suggest Type of Sort
arr1

array([[5, 9, 6],
       [5, 2, 8]])

# Arg

In [47]:
arr1 = np.array([1,4,7,8,3,7,16,12,5,18,11,6])
arr1

array([ 1,  4,  7,  8,  3,  7, 16, 12,  5, 18, 11,  6])

In [48]:
np.argsort(arr1)   #Those are INDEXES

array([ 0,  4,  1,  8, 11,  2,  5,  3, 10,  7,  6,  9], dtype=int64)

In [49]:
np.argmin(arr1)

0

In [50]:
np.argmax(arr1)

9

In [51]:
arr1 = arr1.reshape(4,3)
arr1

array([[ 1,  4,  7],
       [ 8,  3,  7],
       [16, 12,  5],
       [18, 11,  6]])

In [52]:
np.argsort(arr1) 

array([[0, 1, 2],
       [1, 2, 0],
       [2, 1, 0],
       [2, 1, 0]], dtype=int64)

In [53]:
np.argmin(arr1)

0

In [54]:
np.argmax(arr1)

9

In [55]:
np.argsort(arr1, axis=0) 

array([[0, 1, 2],
       [1, 0, 3],
       [2, 3, 0],
       [3, 2, 1]], dtype=int64)

In [57]:
a = np.array([])

In [63]:
a.size

0

In [64]:
if(a.size == 0):
    print('a')

a


In [65]:
np.append(a, [1], 0)

array([1.])

In [66]:
a

array([], dtype=float64)

In [69]:
np.array(range(3,8))

array([3, 4, 5, 6, 7])