In [2]:
import pandas as pd
import numpy as np

In [135]:
l

['ADANIPORTS.csv',
 'ASIANPAINT.csv',
 'AXISBANK.csv',
 'BAJAJ-AUTO.csv',
 'BAJAJFINSV.csv',
 'BAJFINANCE.csv',
 'BHARTIARTL.csv',
 'BPCL.csv',
 'BRITANNIA.csv',
 'CIPLA.csv',
 'COALINDIA.csv',
 'DRREDDY.csv',
 'EICHERMOT.csv',
 'GAIL.csv',
 'GRASIM.csv',
 'HCLTECH.csv',
 'HDFC.csv',
 'HDFCBANK.csv',
 'HEROMOTOCO.csv',
 'HINDALCO.csv',
 'HINDUNILVR.csv',
 'ICICIBANK.csv',
 'INDUSINDBK.csv',
 'INFY.csv',
 'IOC.csv',
 'ITC.csv',
 'JSWSTEEL.csv',
 'KOTAKBANK.csv',
 'LT.csv',
 'MARUTI.csv',
 'MM.csv',
 'NESTLEIND.csv',
 'NTPC.csv',
 'ONGC.csv',
 'POWERGRID.csv',
 'RELIANCE.csv',
 'SBIN.csv',
 'SHREECEM.csv',
 'SUNPHARMA.csv',
 'TATAMOTORS.csv',
 'TATASTEEL.csv',
 'TCS.csv',
 'TECHM.csv',
 'TITAN.csv',
 'ULTRACEMCO.csv',
 'UPL.csv',
 'VEDL.csv',
 'WIPRO.csv',
 'ZEEL.csv']

In [141]:
l1 = ['Adani Ports and Special Economic Zone Ltd.', 'Asian Paints Ltd.',
       'Axis Bank Ltd.', 'Bajaj Auto Ltd.', 'Bajaj Finserv Ltd.',
       'Bajaj Finance Ltd.', 'Bharti Airtel Ltd.',
       'Bharat Petroleum Corporation Ltd.', 'Britannia Industries Ltd.',
       'Cipla Ltd.', 'Coal India Ltd.', "Dr. Reddy's Laboratories Ltd.",
       'Eicher Motors Ltd.', 'GAIL (India) Ltd.',
       'Grasim Industries Ltd.', 'HCL Technologies Ltd.',
       'Housing Development Finance Corporation Ltd.', 'HDFC Bank Ltd.',
       'Hero MotoCorp Ltd.', 'Hindalco Industries Ltd.',
       'Hindustan Unilever Ltd.', 'ICICI Bank Ltd.', 'IndusInd Bank Ltd.','Infosys Ltd.',
       'Indian Oil Corporation Ltd.', 'ITC Ltd.', 'JSW Steel Ltd.',
       'Kotak Mahindra Bank Ltd.', 'Larsen & Toubro Ltd.',
       'Mahindra & Mahindra Ltd.', 'Maruti Suzuki India Ltd.',
       'Nestle India Ltd.', 'NTPC Ltd.',
       'Oil & Natural Gas Corporation Ltd.',
       'Power Grid Corporation of India Ltd.', 'Reliance Industries Ltd.',
       'State Bank of India', 'Shree Cement Ltd.',
       'Sun Pharmaceutical Industries Ltd.', 'Tata Motors Ltd.',
       'Tata Steel Ltd.', 'Tata Consultancy Services Ltd.',
       'Tech Mahindra Ltd.', 'Titan Company Ltd.',
       'UltraTech Cement Ltd.', 'UPL Ltd.', 'Vedanta Ltd.', 'Wipro Ltd.',
       'Zee Entertainment Enterprises Ltd.']

In [142]:

for i in range(50):
    print(l[i],"\t", l1[i])

ADANIPORTS.csv 	 Adani Ports and Special Economic Zone Ltd.
ASIANPAINT.csv 	 Asian Paints Ltd.
AXISBANK.csv 	 Axis Bank Ltd.
BAJAJ-AUTO.csv 	 Bajaj Auto Ltd.
BAJAJFINSV.csv 	 Bajaj Finserv Ltd.
BAJFINANCE.csv 	 Bajaj Finance Ltd.
BHARTIARTL.csv 	 Bharti Airtel Ltd.
BPCL.csv 	 Bharat Petroleum Corporation Ltd.
BRITANNIA.csv 	 Britannia Industries Ltd.
CIPLA.csv 	 Cipla Ltd.
COALINDIA.csv 	 Coal India Ltd.
DRREDDY.csv 	 Dr. Reddy's Laboratories Ltd.
EICHERMOT.csv 	 Eicher Motors Ltd.
GAIL.csv 	 GAIL (India) Ltd.
GRASIM.csv 	 Grasim Industries Ltd.
HCLTECH.csv 	 HCL Technologies Ltd.
HDFC.csv 	 Housing Development Finance Corporation Ltd.
HDFCBANK.csv 	 HDFC Bank Ltd.
HEROMOTOCO.csv 	 Hero MotoCorp Ltd.
HINDALCO.csv 	 Hindalco Industries Ltd.
HINDUNILVR.csv 	 Hindustan Unilever Ltd.
ICICIBANK.csv 	 ICICI Bank Ltd.
INDUSINDBK.csv 	 IndusInd Bank Ltd.
INFY.csv 	 Infosys Ltd.
IOC.csv 	 Indian Oil Corporation Ltd.
ITC.csv 	 ITC Ltd.
JSWSTEEL.csv 	 JSW Steel Ltd.
KOTAKBANK.csv 	 Kotak Mahindra

IndexError: list index out of range

In [97]:
df = pd.read_csv('BAJFINANCE.csv')
df

Date      Symbol Series  Prev Close     Open     High      Low  \
0     2000-01-03  BAJAUTOFIN     EQ       46.95    49.45    50.75    46.50   
1     2000-01-04  BAJAUTOFIN     EQ       50.75    53.20    53.20    47.90   
2     2000-01-05  BAJAUTOFIN     EQ       48.10    46.55    47.40    44.60   
3     2000-01-06  BAJAUTOFIN     EQ       44.60    43.50    46.00    42.10   
4     2000-01-07  BAJAUTOFIN     EQ       45.25    48.00    48.00    42.00   
...          ...         ...    ...         ...      ...      ...      ...   
5230  2021-04-26  BAJFINANCE     EQ     4667.80  4690.00  4829.00  4690.00   
5231  2021-04-27  BAJFINANCE     EQ     4736.55  4747.00  4889.85  4746.55   
5232  2021-04-28  BAJFINANCE     EQ     4865.05  4915.00  5310.00  4915.00   
5233  2021-04-29  BAJFINANCE     EQ     5280.90  5350.00  5525.00  5330.00   
5234  2021-04-30  BAJFINANCE     EQ     5484.85  5350.00  5524.65  5327.70   

         Last    Close     VWAP   Volume      Turnover    Trades  \
0       50.75    50.75    50.05     7600  3.803800e+10       NaN   
1       48.00    48.10    48.56     5000  2.428000e+10       NaN   
2       44.60    44.60    45.47     3500  1.591450e+10       NaN   
3       46.00    45.25    44.43     6200  2.754750e+10       NaN   
4       42.90    42.90    44.44     3500  1.555550e+10       NaN   
...       ...      ...      ...      ...           ...       ...   
5230  4744.00  4736.55  4768.93  2903989  1.384893e+15  175366.0   
5231  4886.00  4865.05  4818.15  2644997  1.274399e+15  148957.0   
5232  5255.00  5280.90  5158.33  8576454  4.424018e+15  466644.0   
5233  5475.00  5484.85  5440.24  7258486  3.948794e+15  392154.0   
5234  5449.00  5451.90  5449.83  4124888  2.247992e+15  233718.0   

      Deliverable Volume  %Deliverble  
0                    NaN          NaN  
1                    NaN          NaN  
2                    NaN          NaN  
3                    NaN          NaN  
4                    NaN          NaN  
...                  ...          ...  
5230            768523.0       0.2646  
5231            777955.0       0.2941  
5232           1420176.0       0.1656  
5233           1537401.0       0.2118  
5234            886610.0       0.2149  

[5235 rows x 15 columns]

In [45]:
arr = df.to_numpy()
arr

array([['2000-01-03', 'BAJAUTOFIN', 'EQ', ..., nan, nan, nan],
       ['2000-01-04', 'BAJAUTOFIN', 'EQ', ..., nan, nan, nan],
       ['2000-01-05', 'BAJAUTOFIN', 'EQ', ..., nan, nan, nan],
       ...,
       ['2021-04-28', 'BAJFINANCE', 'EQ', ..., 466644.0, 1420176.0,
        0.1656],
       ['2021-04-29', 'BAJFINANCE', 'EQ', ..., 392154.0, 1537401.0,
        0.2118],
       ['2021-04-30', 'BAJFINANCE', 'EQ', ..., 233718.0, 886610.0,
        0.2148999999999999]], dtype=object)

In [46]:
stock_features = arr[:,3:8]
stock_features

array([[46.95, 49.45, 50.75, 46.5, 50.75],
       [50.75, 53.2, 53.2, 47.9, 48.0],
       [48.1, 46.55, 47.4, 44.6, 44.6],
       ...,
       [4865.05, 4915.0, 5310.0, 4915.0, 5255.0],
       [5280.9, 5350.0, 5525.0, 5330.0, 5475.0],
       [5484.85, 5350.0, 5524.65, 5327.7, 5449.0]], dtype=object)

In [47]:
from sklearn import linear_model
from sklearn.metrics import mean_absolute_percentage_error

In [48]:
stock_features.shape

(5235, 5)

In [82]:
z = int(0.8*5306)
ler = []
lus[:5]

['ADANIPORTS.csv',
 'ASIANPAINT.csv',
 'AXISBANK.csv',
 'BAJAJ-AUTO.csv',
 'BAJAJFINSV.csv']

In [138]:
lul =[]
for j in l:  
    ler = []
    df = pd.read_csv(j)
    arr = df.to_numpy()
    stock_features = arr[:,3:8]
    for i in range(1,10,1):
        z = int(i/10*5306)
        features_train = stock_features[:z]
        features_test = stock_features[-2:-1]
        stock_label = arr[:,8]
        stock_label
        label_train = stock_label[:z]
        label_test = stock_label[-2:-1]
        model = linear_model.LinearRegression()
        model.fit(features_train, label_train)
        predicted = model.predict(features_test)
        ler.append(mean_absolute_percentage_error(label_test, predicted))
    lul.append(ler)

In [139]:
lul

[[1.7454707855207452e-05,
  0.0004252541785012277,
  0.00044832329121695575,
  0.00044883590782623847,
  0.0004889775262462766,
  0.0005066644298181175,
  0.000685933900993211,
  0.000685933900993211,
  0.000685933900993211],
 [0.004367613515477651,
  0.0029719527703380992,
  0.0016087372436977838,
  0.00036045092785767546,
  0.0006996781657585726,
  0.0011563786374493563,
  0.0011450899184499697,
  0.0011554612610622174,
  0.00115011421746526],
 [0.004965501630863748,
  0.0034830655867967566,
  0.003066704386537879,
  0.002746289740783526,
  0.0029145055366499436,
  0.0029434641219349316,
  0.002904894936147011,
  0.002899255437118285,
  0.002885304515868747],
 [0.002291345252481765,
  0.00297860411786781,
  0.0028261211745034347,
  0.0028701387490815493,
  0.0029185796065274356,
  0.0034428642487023767,
  0.0034118316025842305,
  0.0034118316025842305,
  0.0034118316025842305],
 [0.0025703348352168844,
  0.003601306669474129,
  0.003040709999268308,
  0.0014268261162467437,
  0.00213

In [162]:
stock_label = arr[:,8]
stock_label

array([68.7, 66.35, 63.2, ..., 133.35, 134.8, 137.2], dtype=object)

In [163]:
label_train = stock_label[:z]
label_test = stock_label[-2:-1]

In [164]:
model = linear_model.LinearRegression()
model.fit(features_train, label_train)
predicted = model.predict(features_test)

In [77]:
mean_absolute_percentage_error(label_test, predicted)

0.0006892959118907981

In [32]:
label_test

array([2032.6, 2059.5, 2083.25, 2067.7, 2080.3, 2008.1, 2023.45, 2061.0,
       2144.35, 2085.8, 2101.7, 2106.0, 2202.1, 2175.85, 2178.7, 2191.1,
       2191.05, 2181.95, 2137.6, 2108.9, 2100.6, 2055.35, 2009.1, 2082.0,
       2062.4, 2087.5, 2047.3, 1991.45, 1994.65, 2029.3, 2003.1, 2021.85,
       1992.6, 1984.3, 2002.85, 2005.35, 1982.05, 1911.15, 1931.8, 1944.3,
       1932.1, 1901.7, 1901.15, 1906.4, 1904.35, 1937.85, 1988.65, 1997.3,
       2024.05, 1994.5], dtype=object)

In [ ]:
predicted

In [ ]:
arr

In [ ]:
features = arr[:, np.newaxis, 0+3]
features

In [ ]:
np.append(features, arr[:, np.newaxis, 3+3], 1)

In [ ]:
try:
    np.append(features, arr[:, np.newaxis, 3+3], 1)
except NameError:
    features = arr[:, np.newaxis, 3+3]
print(features)

In [33]:
df.keys()

Index(['Date', 'Symbol', 'Series', 'Prev Close', 'Open', 'High', 'Low', 'Last',
       'Close', 'VWAP', 'Volume', 'Turnover', 'Trades', 'Deliverable Volume',
       '%Deliverble'],
      dtype='object')

In [ ]:
df['Prev Close']

In [ ]:
a = df['Prev Close']
a

In [ ]:
a[1]

In [ ]:
%timeit print(df['Prev Close'])

In [ ]:
%time print(arr[:, 3])

In [17]:
a = np.array([1,2,3])

In [18]:
a

array([1, 2, 3])

In [19]:
a[np.newaxis]

array([[1, 2, 3]])

In [20]:
a = np.array([[]])

In [21]:
a

array([], shape=(1, 0), dtype=float64)

In [22]:
np.append(a, [[1]], 1)

array([[1.]])

In [23]:
a = np.append(a, [[1]], 1)

In [24]:
a = np.append(a, [[2]], 1)

In [25]:
a

array([[1., 2.]])

In [26]:
list(list(2))

TypeError: 'int' object is not iterable

In [28]:
b = 1

In [29]:
[b]

[1]

In [30]:
a = np.array([[]])

In [31]:
a.size

0

In [1]:
def binary_search(l, a):
    print(l)
#     print(l[(len(l)//2)-1])
    if len(l) != 1:
        mid = l[(len(l)//2)-1]
        print(mid, a, mid == a)
        if mid == a:
            return True
        elif mid > a:
            binary_search(l[:(len(l)//2)-1], a)
        else:
            binary_search(l[(len(l)//2):], a)
    else:
        return False

In [2]:
print(binary_search([1,2,3,4,5], 9))

[1, 2, 3, 4, 5]
2 9 False
[3, 4, 5]
3 9 False
[4, 5]
4 9 False
[5]
None
